//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbCliente
    {
        public int Id { get; set; }
        public string NomeCliente { get; set; }
        public string CodigoCliente { get; set; }
        public System.DateTime DataCriacaoCliente { get; set; }
    }
}
